CREATE DATABASE FACTURACION_COMERCIODB
GO
USE FACTURACION_COMERCIODB
GO

CREATE TABLE ARTICULOS(
ID INT PRIMARY KEY IDENTITY (1,1),
NOMBRE VARCHAR (100),
PRECIO_UNITARIO FLOAT)
GO

CREATE TABLE DETALLE_FACTURA(
ID INT PRIMARY KEY IDENTITY (1,1),
ARTICULO_ID INT,
CANTIDAD INT,
PRECIO FLOAT,
FORMA_PAGO_ID INT,
CLIENTE_ID INT,
FACTURA_ID INT,

CONSTRAINT FK_ARTICULO FOREIGN KEY(ARTICULO_ID) REFERENCES ARTICULOS(ID),
CONSTRAINT FK_FACTURA FOREIGN KEY(FACTURA_ID) REFERENCES FACTURAS(ID),
CONSTRAINT FK_FPAGO FOREIGN KEY(FORMA_PAGO_ID) REFERENCES FORMAS_PAGO(ID),
CONSTRAINT FK_CLIENTE FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTES(ID))
GO

CREATE TABLE FORMAS_PAGO(
ID INT PRIMARY KEY IDENTITY (1,1),
NOMBRE VARCHAR (100))
GO

CREATE TABLE CLIENTES(
ID INT PRIMARY KEY IDENTITY (1,1),
DNI VARCHAR (100),
NOMBRE VARCHAR (50),
APELLIDO VARCHAR (50))
GO

CREATE TABLE FACTURAS(
ID INT PRIMARY KEY IDENTITY (1,1),
NRO_FACTURA INT,
FECHA DATETIME)
GO

INSERT INTO FORMAS_PAGO (NOMBRE) VALUES ('Efectivo');
INSERT INTO FORMAS_PAGO (NOMBRE) VALUES ('Tarjeta de Crédito');
INSERT INTO FORMAS_PAGO (NOMBRE) VALUES ('Transferencia Bancaria');

INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('Arroz Integral', 85.50);
INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('Aceite de Oliva 1L', 120.75);
INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('Leche Entera 1L', 45.00);
INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('Pan de Campo', 30.00);
INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('Azúcar 1Kg', 55.25);
INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('Café en Grano 500g', 210.00);
INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('Pasta de Tomate 400g', 35.90);
INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('Harina 1Kg', 60.00);
INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('Galletas de Manteca', 75.50);
INSERT INTO ARTICULOS (NOMBRE, PRECIO_UNITARIO) VALUES ('Jabón en Barra', 25.00);
--------------STORED PROCEDURE--------------

CREATE PROCEDURE SP_OBTENER_FORMAS_PAGO
AS 
BEGIN 
SELECT ID,NOMBRE
FROM FORMAS_PAGO
END
GO

CREATE PROCEDURE SP_ARTICULOS
AS
BEGIN
SELECT ID, NOMBRE, PRECIO_UNITARIO
FROM ARTICULOS
END 
GO

CREATE PROCEDURE SP_OBTENER_FACTURAS
AS 
BEGIN
SELECT ID, NRO_FACTURA, FECHA
FROM FACTURAS
END
GO

CREATE PROCEDURE SP_OBTENER_DETALLE
AS 
BEGIN
SELECT DF.ID, DF.ARTICULO_ID, DF.CANTIDAD, DF.PRECIO, FP.ID AS FORMA_PAGO_ID, FP.NOMBRE AS FORMA_PAGO_NOMBRE,DF.FACTURA_ID, 
       DF.CLIENTE_ID
FROM DETALLE_FACTURA DF
JOIN FORMAS_PAGO FP ON DF.FORMA_PAGO_ID = FP.ID
END
GO

CREATE PROCEDURE SP_CREAR_MAESTRO
@NRO_FACTURA INT,
@FECHA DATE,
@ID INT OUTPUT
AS 
BEGIN
INSERT INTO FACTURAS(NRO_FACTURA,FECHA) VALUES(@NRO_FACTURA,GETDATE())
SET @ID = SCOPE_IDENTITY();
END
GO

CREATE PROCEDURE SP_CREAR_DETALLE
@ARTICULO_ID INT,
@CANTIDAD INT,
@PRECIO FLOAT,
@FORMA_PAGO_ID INT,
@CLIENTE_ID INT,
@FACTURA_ID INT
AS 
BEGIN
INSERT INTO DETALLE_FACTURA(ARTICULO_ID,CANTIDAD,PRECIO,FORMA_PAGO_ID,CLIENTE_ID,FACTURA_ID)
VALUES(@ARTICULO_ID,@CANTIDAD,@PRECIO,@FORMA_PAGO_ID,@CLIENTE_ID,@FACTURA_ID)
END
GO

