CREATE DATABASE BancoAppEC

USE BancoAppEC

CREATE TABLE Cliente(
ID INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
DNI VARCHAR(100)
)

CREATE TABLE TipoCuenta(
ID INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(100)
)

CREATE TABLE Cuenta(
ID INT PRIMARY KEY IDENTITY(1,1),
CBU VARCHAR(100),
SALDO DECIMAL(18,2),
TIPO_CUENTA_ID INT,
ULTIMO_MOVIMIENTO DATETIME,
CLIENTE_ID INT

FOREIGN KEY (TIPO_CUENTA_ID) REFERENCES TIPOCUENTA(ID),
FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
)

CREATE PROCEDURE OBTENER_CLIENTES
AS
BEGIN
SELECT ID, NOMBRE APELLIDO, DNI
FROM Cliente
END

CREATE PROCEDURE TIPO_CUENTAS
AS
BEGIN
SELECT ID, NOMBRE
FROM TipoCuenta
END

CREATE PROCEDURE CUENTAS
AS
BEGIN
SELECT CUENTA.ID, CBU, SALDO, TP.NOMBRE AS NOMBRE_CUENTA, ULTIMO_MOVIMIENTO, CLIENTE_ID
FROM Cuenta
JOIN TipoCuenta TP ON TP.ID = Cuenta.TIPO_CUENTA_ID
END

CREATE PROCEDURE CREAR_CUENTA
@CBU VARCHAR(100),
@SALDO DECIMAL(18,2),
@TIPO_CUENTA_ID INT,
@ULTIMO_MOVIMIENTO DATETIME,
@CLIENTE_ID INT
AS
BEGIN
INSERT INTO Cuenta (CBU, SALDO, TIPO_CUENTA_ID, ULTIMO_MOVIMIENTO, CLIENTE_ID)
VALUES(@CBU, @SALDO, @TIPO_CUENTA_ID, @ULTIMO_MOVIMIENTO, @CLIENTE_ID)
END