use FACTURACION_COMERCIODB
GO

CREATE PROCEDURE SP_AGREGAR_ARTICULO
@NOMBRE VARCHAR,
@PRECIO_UNITARIO FLOAT
AS
BEGIN
	INSERT INTO ARTICULOS(NOMBRE,PRECIO_UNITARIO)
    VALUES (@NOMBRE,@PRECIO_UNITARIO);
END
GO

CREATE PROCEDURE SP_ELIMINAR_PRODUCTO
@ID INT
AS 
BEGIN
     DELETE FROM ARTICULOS
	 WHERE ID=@ID
END
GO
